name: Deployment_Prod

on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build -- -- mode prod

      - name: Deploying application to Amazon S3
        uses: dvelasquez/deploy-s3-action@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_BUCKET_NAME: www.testwyze.com
          DIST_LOCATION_CODE: ./dist
